spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
  application:
   name: product-service
  config:
    import:
    - optional:configserver:http://localhost:8888/

server:
 port: 6767

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
     prefer-ip-address: true

  
  

 

      


      
      
    
      
      
    