server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Temp1234
  jpa:
   hibernate:
    ddl-auto: create
  application:
      name: product-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true  
  

 

      


      
      
    
      
      
    