
server:
  port: 1111
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/javabatch
    username: root
    password: Ambika@91
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format_sql: true
